### ISSUE TITLE
Failure to load PipelineRuns page when several have been created since first page render

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#568] opened 2019-09-26 14:23 UTC
# Expected Behavior
PipelineRuns page loads perfectly every time 

# Actual Behavior
I set multiple (at least 10) PipelineRuns off from a different page 
I tried to go to the PipelineRuns page and it gave me a blank white screen 

# Steps to Reproduce the Problem

1. Create lots of PipelineRuns at once 
2. Try going to PipelineRuns page 
3. Watch as it doesnt load anything 

# Additional Info
This may be intermittent or might be the dashboard has trouble loading the pipelinerun page if there is too many pipelineruns that have not completed running yet 

This is reproducible with just even 3 pipelineruns being created. Seems to be that the UI is not updating in time with all the info received  

<img width="1438" alt="Screenshot 2019-09-26 at 16 00 08" src="https://user-images.githubusercontent.com/32342288/65699989-ceb14e80-e076-11e9-8e19-c6518dc9d7ee.png">

**Comment by AlanGreene** [comment] 2019-09-26 15:46
Looks like it's failing when the PipelineRun is missing status

/assign

**Comment by AlanGreene** [comment] 2019-09-26 16:12
@CarolynMabbott how are you triggering the PipelineRuns used to reproduce this? Are you doing it via kubectl, the dashboard UI, or some other mechanism?

**Comment by CarolynMabbott** [comment] 2019-09-26 16:19
I had one dashboard open and just rebuilt the PipelineRun a few times using the rebuild button
On another window i had a dashboard open and refreshed it onto the PipelineRuns page 

Should work with any PipelineRun, I used it with a hello-world pipeline

**Comment by a-roberts** [comment] 2019-09-27 09:27
Verified and reviewed/merged the PR for this so closing

**Closed by a-roberts** 2019-09-27 09:27 UTC
Labels: kind/bug
