### ISSUE TITLE
Viewing a pipelinerun changes left menu to 'Pipelines"

### ISSUE THREAD

**Issue by dibbles** [tektoncd/dashboard#561] opened 2019-09-26 09:52 UTC
# Expected Behavior

When viewing a pipelinerun, the left menu should stay on PipelineRuns

# Actual Behavior

The left menu changes to Pipelines

# Steps to Reproduce the Problem

1. Go to PipelineRuns
2. Select a PipelineRun (see left menu change to pipelines)
3.

# Additional Info

**Comment by AlanGreene** [comment] 2019-09-26 10:32
Duplicate of https://github.com/tektoncd/dashboard/issues/142#issuecomment-499579502

This a known issue due to the URL scheme we use for the front end.

**Closed by AlanGreene** 2019-09-26 10:32 UTC
