### ISSUE TITLE
Cant install releases into a namespace other than tekton-pipelines

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#1290] opened 2020-04-15 12:51 UTC
# Expected behavior
I can install a release into any namespace

# Actual behavior
It errors when I try and kubectl apply the dashboard release 
```
Carolyns-MacBook-Pro:dashboard carolynmabbott$kubectl apply --filename https://github.com/tektoncd/dashboard/releases/download/v0.6.1/tekton-dashboard-release.yaml -n default
customresourcedefinition.apiextensions.k8s.io/extensions.dashboard.tekton.dev unchanged
clusterrole.rbac.authorization.k8s.io/tekton-dashboard-minimal unchanged
clusterrolebinding.rbac.authorization.k8s.io/tekton-dashboard-minimal unchanged
the namespace from the provided object "tekton-pipelines" does not match the namespace "default". You must pass '--namespace=tekton-pipelines' to perform this operation.
the namespace from the provided object "tekton-pipelines" does not match the namespace "default". You must pass '--namespace=tekton-pipelines' to perform this operation.
the namespace from the provided object "tekton-pipelines" does not match the namespace "default". You must pass '--namespace=tekton-pipelines' to perform this operation.
the namespace from the provided object "tekton-pipelines" does not match the namespace "default". You must pass '--namespace=tekton-pipelines' to perform this operation.
the namespace from the provided object "tekton-pipelines" does not match the namespace "default". You must pass '--namespace=tekton-pipelines' to perform this operation.
Carolyns-MacBook-Pro:dashboard carolynmabbott$ 
```
# Steps to reproduce the problem

1. Try install dashboard 0.6.1 release into a namespace other than tekton-pipelines 
2.
3.

# Environment
- Kubernetes Platform:

docker

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

0.6.1

# Additional Info

**Comment by AlanGreene** [comment] 2020-04-15 14:59
Is this a duplicate of https://github.com/tektoncd/dashboard/issues/930?

**Closed** 2020-04-15 20:42 UTC
Labels: triage/duplicate
