### ISSUE TITLE
External logs not fetched and return "unable to retrieve container logs for containerd"

### ISSUE THREAD

**Issue by fpt-harley-haitx5** [tektoncd/dashboard#3562] opened 2024-08-22 10:45 UTC
# Actual behaviour

We have setup Tekton dashboard with external logs, which will call to another services to retrieve logs from S3 in case logs cannot be retrieved from Tekton pods. However sometimes we still saw this error from dashboard: `unable to retrieve container logs for containerd://xxxxxx`.

We did investigation and saw that Tekton didn't call to external logs service to retrieve logs from S3 (even though correct logs files had been pushed to S3). We tried to open developer tools and found 1 successful request to `https://tekton.example.com/api/v1/namespaces/tekton/pods/<pod_name>/log?container=<container_name>&follow=true` with 200 success code and the response was exactly the message "unable to retrieve container logs for containerd://xxxxxx".

Just to note that when we tried to use kubectl to retrieve the logs from k8s pods, we also received the same message "unable to retrieve container logs for containerd://xxxxxx". So we assume that Tekton treated this message as success logs retrieval and didn't send another requests to external logs service.

# Expected behavior

Tekton should treat return logs from K8s pods "unable to retrieve container logs for containerd://xxxxxx" as error message and send another requests to external logs service.

**Comment by AlanGreene** [comment] 2024-08-22 14:45
Hi @fpt-harley-haitx5. This sounds like an issue with your cluster rather than with the Dashboard.

If the Dashboard receives a successful response from the Kubernetes API when requesting logs, it trusts that this is the actual log content and displays it to the user. The fact that kubectl exhibits the same behaviour confirms this is working as intended in this case.

From the information you've shared it sounds like the pod still exists, otherwise both the Dashboard and kubectl would have given a different result indicating that the pod has been deleted / no longer exists. You can confirm this in the Dashboard by checking the 'Pod' tab of the TaskRun details, or using kubectl.

The fact that the logs returned from the Kubernetes API are not what you expect is beyond the control of the Dashboard, and not something we can reliably detect.

The external logs feature is designed to fallback to the external logs endpoint when the pod has been deleted.

I'm not sure exactly what conditions can cause the logs to become unavailable like this, but I have seen it in the past after certain types of cluster maintenance, or when restarting a local kind cluster during development.

Closing the issue as the Dashboard is working as intended here. Once the pod is deleted it should fallback to your configured external logs endpoint as expected.

**Closed by AlanGreene** 2024-08-22 14:45 UTC
Labels: kind/bug
