### ISSUE TITLE
Being able to view logs after the underlying pod/node has been deleted

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/dashboard#1583] opened 2020-06-30 20:38 UTC
# Describe the solution you'd like

It would be nice to be able to use the dashboard to view logs in the context of pipeline runs / taskruns after the underlying pod/node has been deleted.

Currently the logs are not visible once the pod is no more in the cluster.

# Describe alternatives you've considered

Collecting logs can easily be done outside of the dashboard.
Those logs could be made available to the dashboard through a service so that the dashboard can use this service as a fallback to fetch logs that are not available anymore.

**Comment by AlanGreene** [comment] 2020-06-30 21:16
This one has come up a few times alright.
Duplicate of https://github.com/tektoncd/dashboard/issues/232

**Closed** 2020-06-30 21:16 UTC
Labels: kind/feature, triage/duplicate
