### ISSUE TITLE
dashboard logout redirect url error

### ISSUE THREAD

**Issue by gsgs-libin** [tektoncd/dashboard#2434] opened 2022-09-04 07:02 UTC
According to this document: https://github.com/tektoncd/dashboard/blob/main/docs/walkthrough/walkthrough-oauth2-proxy.md

cliek logout redirect to : http://auth.127.0.0.1.nip.io

but normal should be：http://tekton-dashboard.127.0.0.1.nip.io

**Comment by AlanGreene** [comment] 2022-09-04 08:40
Thanks for opening this issue @gsgs-libin. Can you clarify what the problem is?

Are you talking about this section in the walk-through? https://github.com/tektoncd/dashboard/blob/main/docs/walkthrough/walkthrough-oauth2-proxy.md#configuring-dashboard-logout-url

The URL provided is correct, the `/oauth2/sign_out` endpoint is provided by the oauth2-proxy which is accessed at `auth.127.0.0.1.nip.io`.

**Comment by gsgs-libin** [comment] 2022-09-05 01:24
in my case:

oauth url : tekton-oauth.meitu.com
dash url : tekton-dashboard.meitu.com

1. sign in is ok

![企业微信截图_43c29e3d-18f0-4504-9a18-ad266d8d9032](https://user-images.githubusercontent.com/22513159/188342755-cf0dadec-8a90-4501-965f-0b2849b15aac.png)


2.when logout, and sign again , it will return 404 page (in oauth url)

![企业微信截图_69ae4d87-2bab-413b-bbf5-07114da6986d](https://user-images.githubusercontent.com/22513159/188342727-11d6d439-0a4e-4e21-851b-e1ba920dd209.png)

![企业微信截图_30ab9579-f7cb-41ec-a35a-bb2eeaba9de2](https://user-images.githubusercontent.com/22513159/188342730-ac7e82e6-c8fc-4761-8254-ab292169adb7.png)

**Comment by AlanGreene** [comment] 2022-09-05 08:28
If you want to redirect to the Dashboard login again after completing the logout process you will need to instruct the oauth2-proxy that this is what you want by adding the redirect parameter on the logout URL, for example:

`https://tekton-oauth.meitu.com/oauth2/sign_out?rd=https%3A%2F%2Ftekton-dashboard.meitu.com`

Closing the issue and re-labelling as this is not a bug with the Dashboard, rather a question about configuring the oauth2-proxy. Let me know if you have any other questions.

**Closed by AlanGreene** 2022-09-05 08:28 UTC
Labels: kind/question

**Comment by gsgs-libin** [comment] 2022-09-06 01:47
> If you want to redirect to the Dashboard login again after completing the logout process you will need to instruct the oauth2-proxy that this is what you want by adding the redirect parameter on the logout URL, for example:
> 
> `https://tekton-oauth.meitu.com/oauth2/sign_out?rd=https%3A%2F%2Ftekton-dashboard.meitu.com`
> 
> Closing the issue and re-labelling as this is not a bug with the Dashboard, rather a question about configuring and using the oauth2-proxy. Let me know if you have any other questions.

thank you,it works, is my configuration error!
