### ISSUE TITLE
Tekton dashboard is refreshing about every minute especially on VPN

### ISSUE THREAD

**Issue by mtamboli** [tektoncd/dashboard#736] opened 2019-11-13 19:20 UTC
# Expected Behavior
Dashboard should not get refreshed. Talked to @a-roberts on this. 

# Actual Behavior
Dashboard gets refreshed and you loose the work in progress. For example, if you are creating a webhook, you will have to restart unless you finish the task before the refresh.

# Steps to Reproduce the Problem

1. Keep the Tekton dashboard open on Chrome or safari
2. You will see refresh happening after a minute or so
3. This happened consistently when connected on VPN

# Additional Info

![image](https://user-images.githubusercontent.com/29490950/68796300-9e227580-0620-11ea-87b7-6ccdd80256ac.png)

**Comment by AlanGreene** [comment] 2019-11-13 19:31
From the screenshot it looks like your websocket connection is getting disconnected (request to ws://<host>/v1/websockets/resources). When this happens and the connection is re-established, the dashboard will make requests in the background to fetch the latest state of resources that may have changed during the disconnect. This may cause some parts of the UI to update to show the new information but should not cause a full page refresh.

@mtamboli @a-roberts can you provide more details on the behaviour experienced? Is this only affecting the webhooks extension pages or is this behaviour also present on core dashboard pages?

**Comment by mtamboli** [comment] 2019-11-13 19:39
I noticed this when creating webhook but pretty sure it is happening on other pages also like looking at PipelineRuns.

**Comment by AlanGreene** [comment] 2019-11-13 21:33
I managed to reproduce some issues that sound similar to what you've described on the PipelineRuns page against a local environment by disabling and re-enabling the port-forward to the dashboard service.

PR open to address those: https://github.com/tektoncd/dashboard/pull/737
Specifically this should prevent the Create PipelineRun dialog from being reset / closed on reconnect, and prevent the PipelineRuns list from momentarily reverting to a blank / loading state on reconnect.

@a-roberts I'm not seeing anything obvious in the webhook extensions code similar to the reset in PipelineRuns.

**Comment by a-roberts** [comment] 2019-11-14 11:19
@AlanGreene many thanks for the dashboard fix which is now merged, I'm not seeing anything obvious either on the extension side. On the webhook page we do a call to fetch webhooks on componentDidMount. I'm going to open a followup issue to investigate things on the webhooks extension side specifically and close this.

**Closed by a-roberts** 2019-11-14 11:19 UTC
Labels: kind/bug
