### ISSUE TITLE
What version should I use with Tekton 0.9.2?

### ISSUE THREAD

**Issue by DenisPalnitsky** [tektoncd/dashboard#1154] opened 2020-03-17 14:42 UTC
# Expected behavior
I know what version of dashboard to use if I use Tekton 9.2

# Actual behavior
I can't see it on Readme

# Steps to reproduce the problem

1. Install Tekton 9.2
2. Try to figure out what dashboard version should you use 

# Environment
- Tekton Pipelines version: 0.9.2

Tekton 0.9.2 is missing in readme section https://github.com/tektoncd/dashboard#which-version-should-i-use

**Comment by a-roberts** [comment] 2020-03-17 14:53
Hey Denis, we unfortunately never did a 0.9.2 release, there were issues to do with PullRequest resources (supporting SCMs other than github.com for example), is there a reason you'd like to continue using 0.9.2 in particular and not move up to 0.10.1?

**Comment by DenisPalnitsky** [comment] 2020-03-17 15:03
We want to upgrade Tekton from version 0.7, used by our application, with minimum code changes. Version 0.9.2 is the best candidate for this.

**Comment by a-roberts** [comment] 2020-03-17 15:26
Ah, I see, so you could build from an older revision, https://github.com/tektoncd/dashboard/commit/3cfadda5a940eca9512abe622b0749a5c324d186 this is when the commit went in to bump us to use Tekton 0.10.

The repository at this previous commit https://github.com/tektoncd/dashboard/commit/ad58fed81e84c7b87d09e8cb81fa581e0edaab34 is my best guess at what would work for you.

IDK how familiar you are with the process or developing with Go, but I would clone this repository  to this kind of directory structure, assuming your GOPATH is $HOME/go:
```
(base) Adams-MBP:dashboard aroberts$ pwd
$HOME/go/src/github.com/tektoncd/dashboard
```

then checkout that commit and build with

```
npm ci && dep ensure -v && npm run build_ko
```

before ko applying - you would want to check out `DEVELOPMENT.md` at that point in the repository if you're looking for any further guidance (for example, how to get the pre-reqs).

Unfortunately there are no plans in mind (at least for us as core contributors that can build and publish the releases that result in images we reference in the GitHub releases) to have a 0.9.2 Dashboard release for the reasons above (the regression in Pipelines), but contributions are always welcome.  Let us know what you think anyways and if this works for you.

**Comment by DenisPalnitsky** [comment] 2020-03-18 16:04
Building from code is the last resort for us. 
What Dashboard release would you recommend for tekton 0.9.2 v0.4.1 or v0.5.0 ?

**Comment by a-roberts** [comment] 2020-03-18 16:17
> Building from code is the last resort for us.
> What Dashboard release would you recommend for tekton 0.9.2 v0.4.1 or v0.5.0 ?

Yeah that's understandable, I would try the latest (v0.5.3) but be wary you may have issues with, at least, the rerun function - give that a go and we can update the docs if things work out well for you

**Comment by DenisPalnitsky** [comment] 2020-03-18 16:27
Re-run does not work in 0.4.1, 0.5.0 and 0.5.3

**Comment by AlanGreene** [comment] 2020-06-23 14:50
Closing this since there's no further action here for the Dashboard. If you did find a solution that worked for you it would be great if you could share in case others may find it useful.

Current Dashboard releases support Pipelines v0.11 - 0.13.

**Closed by AlanGreene** 2020-06-23 14:50 UTC
