### ISSUE TITLE
Not working with taskSpec ?

### ISSUE THREAD

**Issue by eddycharly** [tektoncd/dashboard#1159] opened 2020-03-18 11:19 UTC
is it just me or the dashboard does not work with pipeline runs that declare task spec declared inline ?

**Comment by AlanGreene** [comment] 2020-03-18 12:19
We should support inline definitions, and we've made some changes to support this in the past for inline Pipeline specs, and inline Task specs.

It's possible we've missed some cases. Can you share an example of one you're expecting to work as well as a screenshot of the behaviour you're seeing?

**Comment by AlanGreene** [comment] 2020-03-18 13:38
Looks like we're not handling this well, see https://github.com/tektoncd/pipeline/blob/master/examples/v1alpha1/pipelineruns/pipelinerun-with-pipelinespec-and-taskspec.yaml for an example

**Comment by eddycharly** [comment] 2020-03-18 13:43
Sure,
I am using prow, it is prow so there is some prow syntax here but it shouldn't really matter i guess.
```yaml
buildTaskSpec: &buildTaskSpec
  inputs:
    resources:
      - name: src
        type: git
    params:
      - name: s3path
        type: string
  steps:
    - name: make-build
      image: xxx/php-node-ci
      workingDir: /workspace/src
      script: |
        #!/usr/bin/env bash
        set -e
        make -f tekton.makefile build
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-oauth-token
              key: oauth
      volumeMounts:
        - name: cache-composer
          mountPath: /tmp
      resources:
        requests:
          memory: 1Gi
          cpu: 1
        limits:
          cpu: 1
    - name: make-unit-tests
      image: xxx/php-node-ci
      workingDir: /workspace/src
      script: |
        #!/usr/bin/env bash
        set -e
        make -f tekton.makefile unit-tests
    - name: make-integration-tests
      image: xxx/php-node-ci
      workingDir: /workspace/src
      script: |
        #!/usr/bin/env bash
        set -e
        make -f tekton.makefile integration-tests
    - name: make-package
      image: xxx/php-node-ci
      workingDir: /workspace/src
      script: |
        #!/usr/bin/env bash
        set -e
        make -f tekton.makefile package
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-oauth-token
              key: oauth
      volumeMounts:
        - name: cache-composer
          mountPath: /tmp
    - name: upload-packages
      image: xxx/alpine-utils
      workingDir: /workspace/src
      script: |
        #!/usr/bin/env sh
        set -e
        aws --region eu-central-1 s3 cp package.zip $(inputs.params.s3path) --only-show-errors
  volumes:
    - name: cache-composer
      nfs:
        server: some.nfs.server
        path: /

presubmits:
  - name: pull-ci
    agent: tekton-pipeline
    always_run: true
    skip_report: false
    rerun_command: /run pull-ci
    trigger: "(?m)^/run (all|pull-ci),?(\\s+|$)"
    pipeline_run_spec:
      pipelineSpec:
        params:
          - name: PULL_NUMBER
            type: string
          - name: PULL_PULL_SHA
            type: string
        resources:
          - name: src
            type: git
        tasks:
          - name: build
            taskSpec: *buildTaskSpec
            params:
              - name: s3path
                value: s3://some.s3.bucket/api/pull/$(params.PULL_NUMBER)/$(params.PULL_PULL_SHA)/
            resources:
              inputs:
                - name: src
                  resource: src
      resources:
        - name: src
          resourceRef:
            name: PROW_IMPLICIT_GIT_REF
```

When prow runs this pipeline, it apears in the dashboard
![image](https://user-images.githubusercontent.com/47974576/76966598-86d4fb00-6926-11ea-83ad-ad56482afa80.png)

but if i click on it

![image](https://user-images.githubusercontent.com/47974576/76966735-b4ba3f80-6926-11ea-9dde-072907eb966d.png)

The task runs appear correctly under the TaskRuns though.

It could be related to prow but i don't think so, prow simply creates the pipeline run using the tekton client.

Thanks

**Comment by eddycharly** [comment] 2020-03-19 07:22
Shall I try to open a pr or someone is already working on a fix ?

**Comment by AlanGreene** [comment] 2020-03-19 12:19
If you wanted to contribute a fix that would be fantastic. I just took a quick look and it seems like this would be a great place to start: https://github.com/tektoncd/dashboard/blob/06b33899e7a14c959116c59847293630391301d1/packages/components/src/components/PipelineRun/PipelineRun.js#L114

The code is assuming there's a `taskRef` when it shouldn't.

**Comment by eddycharly** [comment] 2020-03-19 12:21
Thanks for pointing me in the right direction. 
I will try to look at it this afternoon.

**Comment by eddycharly** [comment] 2020-03-19 14:05
I'm trying to run the dashboard locally, is this possible to point to a remote for fetching pipelineruns, taskruns, etc... ?

Right now, all requests go to http://localhost:8000, i would like to fetch objects from my remote tekton dashboard backend.

**Comment by AlanGreene** [comment] 2020-03-19 14:11
In dev mode for the front end (`npm start`) we use webpack-dev-server and proxy all API requests to `localhost:9097`

Assuming your kubectl context is set to your remote cluster, you should be able to run something like this to expose your dashboard backend on port 9097 locally

`kubectl --namespace tekton-pipelines port-forward service/tekton-dashboard 9097:9097`

**Comment by eddycharly** [comment] 2020-03-19 14:13
Awesome, works fine, thanks !
I tried changing `API_DOMAIN` in `config.json` but it was not working for some certificate related reasons.

**Comment by eddycharly** [comment] 2020-03-19 19:48
I think the issue starts here https://github.com/tektoncd/dashboard/blob/06b33899e7a14c959116c59847293630391301d1/src/containers/PipelineRun/PipelineRun.js#L206

What do you think ?

**Comment by eddycharly** [comment] 2020-03-19 20:10
@AlanGreene removing the filter in the container and accounting for taskSpec in the component fixes the issue.

Now, the only thing i don't know is here, as i don't really have a taskName at hand in the case of taskSpec :
https://github.com/tektoncd/dashboard/blob/06b33899e7a14c959116c59847293630391301d1/packages/components/src/components/PipelineRun/PipelineRun.js#L165

**Comment by AlanGreene** [comment] 2020-03-19 21:04
I have a feeling that `taskName` isn't actually used anywhere else and could be safely removed, I can double-check tomorrow (GitHub search isn't great for that kind of thing, even less so on mobile...)

**Comment by eddycharly** [comment] 2020-03-19 21:15
I think you're right, for testing i hard coded a random `taskName` but it didn't appear anywhere on the dashboard.

**Comment by AlanGreene** [comment] 2020-03-20 11:05
Confirmed it's not used, safe to go ahead and remove it 👍

**Comment by AlanGreene** [comment] 2020-03-23 17:18
PR merged, thanks @eddycharly

**Closed by AlanGreene** 2020-03-23 17:18 UTC
Labels: kind/bug
