### ISSUE TITLE
Allow filtering with regex/match pattern

### ISSUE THREAD

**Issue by fpt-dylan-datnt305** [tektoncd/dashboard#3478] opened 2024-06-26 09:32 UTC
# Feature request
What I want to achieve is that I can search the pipeline run using regex

# Use case

Currently, I'm assigning several labels to our pipeline runs. We have quite many pipeline runs for our apps so it would be really difficult to find out which pipeline run. As of now, whenever I want to search for a pipeline run, I have to use the full value of the label to find exactly. What I want to achieve is that I can search the pipeline run using regex (e.g. name:ci-pull-request-*) would return a list of pipeline run that have label is "name" and have value that starts with "ci-pull-request-". Currently when I try to use asterisk to find all, it gets Bad Request like image below.
<img width="1177" alt="image" src="https://github.com/tektoncd/dashboard/assets/171474107/9e30360e-6e9d-4b11-860c-20e625ed081d">

**Comment by AlanGreene** [comment] 2024-06-26 09:48
Hi @fpt-dylan-datnt305, thanks for the feature request. The Dashboard relies on Kubernetes' APIs to retrieve the resources, and Kubernetes does not support this type of advanced filtering.

Doing the filtering in the Dashboard client doesn't really make sense as we would still need to load the full set of resources before processing.

The only options currently are:
- label selectors (Dashboard currently supports equality-based) https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
- field selectors (very limited, although this may be [enhanced in a future Kubernetes release](https://github.com/kubernetes/kubernetes/issues/53459)) https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/

We do have another issue to improve the UI handling of labels for filtering / navigation, see https://github.com/tektoncd/dashboard/issues/1428 for details, including one option we were considering for an improved filtering experience.

Closing this as a duplicate of that issue, feel free to comment there with any additional requirements or suggestions not already covered.

**Closed by AlanGreene** 2024-06-26 09:48 UTC
Labels: kind/feature
