### ISSUE TITLE
Tekton Rebuild - 403 denied 

### ISSUE THREAD

**Issue by tppalani** [tektoncd/dashboard#3192] opened 2023-11-02 16:51 UTC
# Expected behavior
Tekton previous build pipelinerun should be re-run from TekTon GUI

# Actual behaviour
I'm not able to re-run the tekton pipeline using previous successful history, error message say from the browser inspect.
Note: I can able to run the pipeline using pipelinerun.yaml

# Steps to reproduce the bug

1.
2.
3.

# Additional info

- Kubernetes version: 

  **Output of `kubectl version`:**
  ```
  1.26
v0.38.0
  ```

- Tekton versions:

  **Output of `tkn version` or**
  ```sh
  kubectl get deploy tekton-pipelines-controller -n tekton-pipelines -o=jsonpath="{\"Pipeline version: \"}{.metadata.labels.version}{\"\n\"}"

  kubectl get deploy tekton-triggers-controller -n tekton-pipelines -o=jsonpath="{\"Triggers version: \"}{.metadata.labels.version}{\"\n\"}"

  kubectl get deploy tekton-dashboard -n tekton-pipelines -o=jsonpath="{\"Dashboard version: \"}{.metadata.labels.version}{\"\n\"}"
  ```

  ```
 Pipeline version: v0.48.0
Dashboard version: v0.38.0
Triggers version: NA
  ```

**Comment by AlanGreene** [comment] 2023-11-03 16:00
Hi @tppalani, is this the same issue discussed on Slack? https://tektoncd.slack.com/archives/CJ62C1555/p1698939993598889

Closing as resolved. It was a misconfiguration on the cluster and not a bug with the Dashboard.

If I'm mistaken and this is a different issue feel free to reopen with additional context.

**Closed by AlanGreene** 2023-11-03 16:00 UTC
Labels: kind/bug
