### ISSUE TITLE
If you delete a pipeline before deleting webhook associated to pipline, it causes pipeline to run, despite pipeline not existing

### ISSUE THREAD

**Issue by oiricaud** [tektoncd/dashboard#1282] opened 2020-04-10 22:42 UTC
# Expected behavior
As a user, I should be able to delete a webhook that is associated to a pipeline that does not exist, but instead I get `Check the webhook(s) existed and both the dashboard and extension pods are healthy.`

# Actual behavior
As a user I am currently not able to delete a webhook associated with a pipeline that does not exist. 

# Steps to reproduce the problem

1. Create pipeline, trigger bindings, trigger templates and task runs `abc-pl`, `abc-pull-binding`, `abc-push-binding` `abc-template-binding` 
2.  Create a webhook and associate webhook to pipeline `abc-pl`
3. Delete pipeline `abc-pl`
4. Go to webhooks and you should get something similar to this: 

<img width="1198" alt="Screen Shot 2020-04-10 at 5 36 27 PM" src="https://user-images.githubusercontent.com/11867058/79027447-d12a5000-7b51-11ea-9950-526a81ec7fd4.png">

The pipeline is missing and weird shannigans are happening in the tekton-ui dashboard. 

# Environment
- Kubernetes Platform:

`Openshift 4.3.5`

- Tekton Pipelines version:

Client version: 0.8.0

- Tekton Triggers version:

not sure how to check the version... 
- Tekton Dashboard version:

not sure how to check the version... 

# Additional Info

**Comment by AlanGreene** [comment] 2020-04-11 00:56
Hi @oiricaud, thanks for reporting.

This was fixed in the 0.5.3 dashboard + webhooks extension releases, closing as a duplicate of  https://github.com/tektoncd/dashboard/issues/1137.

---

> not sure how to check the version

This wasn't easy in older releases. You can get the image URL from the dashboard pod, e.g.:
```
kubectl get pod -n tekton-pipelines -l 'app=tekton-dashboard' -ojson | jq '.items[0].spec.containers[0].image'

"gcr.io/tekton-releases/github.com/tektoncd/dashboard/cmd/dashboard@sha256:7adaaa75759b04a6003a0334e2843582a160b2d95a18943a49bed3b9c047b343"
```

If you open the gcr.io URL in your browser you'll see the corresponding version tag listed:
![image](https://user-images.githubusercontent.com/2829095/79031465-b0381e00-7b96-11ea-9019-09f73afa1ec0.png)


Recent versions (0.5.1+) of the dashboard now have an About page listed in the main nav which shows the dashboard, pipeline, and triggers versions for convenience.

![image](https://user-images.githubusercontent.com/2829095/79031527-289edf00-7b97-11ea-8528-b80d63bccc73.png)
You can also find the version as a label on the dashboard deployment, e.g. `kubectl get -n tekton-pipelines deployment tekton-dashboard -ojson | jq '.metadata.labels.version'`

**Closed by AlanGreene** 2020-04-11 00:56 UTC
