### ISSUE TITLE
Trigger PipelineRun with Workspace option

### ISSUE THREAD

**Issue by fpt-dylan-datnt305** [tektoncd/dashboard#3477] opened 2024-06-26 09:27 UTC
# Feature request

I want to have options to specify workspace when create pipeline run on Dashboard UI.

# Use case

Currently whenever I want to create pipeline run on Dashboard UI, I can only specify params, labels, name, etc... but missing one important thing is workspace binding part. This leads to the issue that the pipeline run would fail immediately because of lacking required workspace. We already have defined required workspace in our pipeline so I want a feature so that whenever I create a pipeline run from a pipeline on dashboard, those workspace will exists and I can choose to bind a volume claim or secret, etc. to the pipeline run.
# Alternatives

I can work around this by using YAML mode but this would not utilize the power of using UI. It would make more overhead to our dev when they want to manually trigger a pipeline run.

# Additional context

<img width="1153" alt="image" src="https://github.com/tektoncd/dashboard/assets/171474107/4e0cdee1-b303-4fad-9015-5a30e552e6a6">

**Comment by AlanGreene** [comment] 2024-06-26 09:43
Thanks for the feature request @fpt-dylan-datnt305, this is a duplicate of https://github.com/tektoncd/dashboard/issues/3477 so closing. Feel free to add any comments or feedback on that issue if your needs are not already addressed there.

**Closed by AlanGreene** 2024-06-26 09:43 UTC
Labels: kind/feature

**Comment by fpt-dylan-datnt305** [comment] 2024-06-26 09:47
> Thanks for the feature request @fpt-dylan-datnt305, this is a duplicate of #3477 so closing. Feel free to add any comments or feedback on that issue if your needs are not already addressed there.

This #3477 you are saying is referring to my own issue??

**Comment by AlanGreene** [comment] 2024-06-26 09:51
Apologies, bad copy-paste, I meant https://github.com/tektoncd/dashboard/issues/1283
