### ISSUE TITLE
Add IDs to Web elements (Required for automation scripts)

### ISSUE THREAD

**Issue by rnapoles-tktn** [tektoncd/dashboard#925] opened 2020-01-20 17:21 UTC
Problem:
Many web elements are not assigned IDs. The use of IDs provide reliability to automated test scrips so that the automation can consistently set focus on elements.

Expected:
Please add IDs to the following web elements:
Left menu:
- [x] Tekton dropdown
- [x] Pipelines menu option
- [x] PipelineRuns menu option
- [x] PipelineResources menu option
- [x] Tasks menu option
- [x] ClusterTasks menu option
- [x] TaskRuns menu option
- [ ] Namespaces 
   NameSpaceDropdownMenu although it has an ID please use the proper SELECT tag as the current use of DIV tag does not allow automation to send text to the web element. See issue 903 https://github.com/tektoncd/dashboard/issues/903
- [x] Import Tekton Resources menu option
- [x] Secrets menu option
- [x] ServiceAccounts menu option
- [x] Webhooks menu option

Under PipelineRuns panel:
- [ ] Search input field has an ID but includes some random characters at the end, please rename from id="search__input__id_njjw8huh54" to id="search__input"
- [x] Add ID for "Add filter +" button
- [x] Add ID for Inline-notification (notification to display error message when clicking add filter with an invalid level)
- [x] Add ID for "Create PipelineRun +" button
- [ ] Add IDs to each column for each returned row (add index to each ID)

Create PipelineRun dialog:
- [ ] Namespace Dropdown please use SELECT tag and assign the ID to the Select tag
- [ ] Select Pipeline dropdown please use SELECT tag and assign the existing ID to it
- [ ] Pipeline dropdown please use SELECT tag and assign existing ID to it
- [ ] Git pipeline resource dropdown, please use SELECT tag and assign existing ID to it
- [ ] docker-image pipeline resource dropdown, please use SELECT tag and assign existing ID to it
- [ ] Remove random characters from IDs for label Key and Value fields
- [ ] Use SELECT tag for Select Service account dropdown and assign the ID to select tag
- [ ] Add ID to create button
- [ ] Add ID to cancel button

Pipeline Resources panel:
- [ ] Add IDs to each column for each returned row (add index to each ID)

Tasks Panel:
- [ ] Add IDs to each column for each returned row (add index to each ID)

Cluster Tasks:
- [ ] Add IDs to each column for each returned row (add index to each ID)

TaskRuns panel:
- [ ] Add IDs to each column for each returned row (add index to each ID)

Import Tekton Resources panel:
- [ ] Namespace dropdown, use SELECT tag and assign the existing ID to it
- [ ] Select Service Account dropdown, use SELECT tag and assign the existing ID to it
- [x] Add ID to "Import and Apply" button

Secrets panel:
- [ ] Add ID to "Add secret +" button

Create Secrets dialog:
- [ ] Rename ID for secret name from name to secret-name
- [ ] Namespace dropdown, please use SELECT tag and assign the existing ID to it
- [ ] AccessTo dropdown, please use SELECT tag and assign the existing ID to it
- [ ] Add ID to "Add" Server URL button
- [ ] Add ID to Remove" Server URL button
- [ ] Remove random characters from IDs for label Key and Value fields

ServiceAccounts panel:
- [ ] search input field, remove random characters from ID
- [x] Add ID to "Add filter +"button
- [ ] Add index to IDs for all service accounts listed in the table.

Webhooks panel:
- [ ] The Id for the Name field is "id" please change to something more descriptive like webhook-name for example
- [ ] Select secret dropdown, please use SELECT tag and assign ID to it, replace the current git ID value to select-secret
- [ ] Select namespace dropdown, please use the SELECT tag and assign the existing ID to it
- [ ] Select pipeline dropdown, please use the SELECT tag and assign the existing ID to it
- [ ] Select service account dropdown, please use the SELECT tag and assign the existing ID to it

**Comment by a-roberts** [comment] 2020-01-28 11:19
Hmm, based on https://github.com/tektoncd/dashboard/issues/903 are we sure we want to do this @rnapoles-tktn @AlanGreene?

Can we really not use Selenium to select the user visible components instead? 

Yeah, we could go about adding all of these IDs (I've ticked off all the trivial ones) but I'm not convinced we should - with Jest for example we use getByText where we can as opposed to getById/getByTestId.

**Comment by AlanGreene** [comment] 2020-01-28 12:42
I have a few concerns:

- this automation is not run as part of our build / release process so there's nothing to catch breaking changes
- in cases where we already provide an ID to a Carbon component, it may use this as a base value and append additional content (sometimes random) to its child elements as described in some of the items above. We do not always have direct control over how Carbon uses the ID internally. The DataTable component, for example, currently gives each cell an ID by combining the row and column IDs.
- adding index-based IDs doesn't make sense in a lot of cases. This is especially true when we introduce sorting as the same content could be displayed at a different locations in the list depending on the sort order.
- some of the proposed changes are not desired (e.g. the Dropdown to Select change as Adam mentions) and would have a negative impact on the user experience and our ability to provide certain functionality
- in many of the cases where it appears trivial to add an ID (e.g. the side nav), it's not clear what advantage this gives over using the content that's already available

I'm happy to discuss this and find an approach that works, but I don't think adding IDs to everything is the answer or even possible in all cases.

**Comment by a-roberts** [comment] 2020-01-28 14:39
Thanks Alan, so @rnapoles-tktn today on our scrum mentioned (and can perhaps add more here if I've missed anything) that the issue is when there's no text to select I believe, I don't think a solution was suggested around the dropdowns though which is likely causing Rodolfo the most pain currently

Note that I'm holding off on implementing this atm until we've got a good direction to go with

**Comment by rnapoles-tktn** [comment] 2020-01-29 14:20
@AlanGreene @a-roberts  Regarding Alan's feedback:

- This is to implement regression test suites and will address accessibility testing at the same time
- Yes, we can use xpaths and take advantage of existing IDs (if any available) as a starting point and build up the full xpath of the target element. However if the UI changes between the element defined with an ID and the target element then the xpath becomes invalid, making the automation unreliable and increases cost of maintenance. 
- I agree with the problem described about using index for tables, that gets resolved with the combined IDs.
- The current implementation of dropdown elements block the automation. For instance, tespite the fact that namespace has an ID, I can not expand the dropdown (can not click on element error) and I can not send text so select a value, or send the down key (which is not a good option as the position of values changes when adding namespaces) as there is no way to expand the dropdown and no way to select an option from the dropdown. 
- 

With that said, let me try one more thing for the dropdown elements and will add more information.

**Comment by AlanGreene** [comment] 2020-06-23 14:59
Since the last discussions on this topic we have made significant updates to the UI, including taking on some pretty substantial Carbon updates. These have altered both the user experience as well as some of the underlying DOM structure and Carbon's use of ids.

Closing as there's no current plan to implement the remainder of the changes as described in this issue.

**Closed by AlanGreene** 2020-06-23 14:59 UTC
