### ISSUE TITLE
Unable to import pipeline and tasks while following the Minikube tutorial

### ISSUE THREAD

**Issue by R3DRUN3** [tektoncd/dashboard#2898] opened 2023-05-03 08:26 UTC
I am following the official minikube <a href="https://github.com/tektoncd/dashboard/blob/main/docs/tutorial.md">tutorial</a> step by step.
# Expected behavior
The resources (pipeline and tasks) are imported without errors.
# Actual behaviour
Import procedure give the following error:
```json
{"level":"error","ts":1683100770.1274495,"caller":"git/git.go:53","msg":"Error running git [init /workspace/repo]: exit status 1\n/workspace/repo/.git: Permission denied\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:53\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:88\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:250"}
{"level":"fatal","ts":1683100770.1275294,"caller":"git-init/main.go:54","msg":"Error fetching git repository: exit status 1","stacktrace":"main.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:54\nruntime.main\n\truntime/proc.go:250"}
```
# Steps to reproduce the bug

1. follow the official minikube <a href="https://github.com/tektoncd/dashboard/blob/main/docs/tutorial.md">tutorial</a> step by step up until the `Import some Tekton resources using the Tekton Dashboard` step

# Additional info

- Kubernetes version:

  **Output of `kubectl version`:**
 ```console
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:21:19Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
 ```

- Tekton versions:

  **Output of `tkn version`**
```console
Client version: 0.30.1
Pipeline version: v0.47.0
Dashboard version: v0.35.0
```

# Other infos
tekton pods are all up and running:
```console
kubectl get pods --namespace tekton-pipelines

NAME                                          READY   STATUS    RESTARTS   AGE
tekton-dashboard-5959c4fbdb-vbrwp             1/1     Running   0          82m
tekton-pipelines-controller-9659dd7c8-2qwz8   1/1     Running   0          86m
tekton-pipelines-webhook-5647bc9947-kg4dd     1/1     Running   0          86m
```

kubernetes events after the import:
```console
kubectl get events --sort-by='.metadata.creationTimestamp' -A 

tekton-dashboard   30s         Normal    Started                   pipelinerun/import-resources-1683102212284                  
tekton-dashboard   28s         Normal    Pending                   taskrun/import-resources-1683102212284-fetch-repo           pod status "Initialized":"False"; message: "containers with incomplete status: [prepare place-scripts]"
tekton-dashboard   28s         Normal    Scheduled                 pod/import-resources-1683102212284-fetch-repo-pod           Successfully assigned tekton-dashboard/import-resources-1683102212284-fetch-repo-pod to minikube-m03
tekton-dashboard   28s         Normal    Pulled                    pod/import-resources-1683102212284-fetch-repo-pod           Container image "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.47.0@sha256:5282e057d67e18632b4158994d5a4af50799568d67fcc6db4da53004ae5f4dd5" already present on machine
tekton-dashboard   28s         Normal    Scheduled                 pod/affinity-assistant-9b19aeb6cb-0                         Successfully assigned tekton-dashboard/affinity-assistant-9b19aeb6cb-0 to minikube-m03
tekton-dashboard   28s         Normal    Created                   pod/import-resources-1683102212284-fetch-repo-pod           Created container prepare
tekton-dashboard   28s         Normal    Started                   pod/import-resources-1683102212284-fetch-repo-pod           Started container prepare
tekton-dashboard   27s         Normal    Pending                   taskrun/import-resources-1683102212284-fetch-repo           pod status "Initialized":"False"; message: "containers with incomplete status: [place-scripts]"
tekton-dashboard   27s         Normal    Pulled                    pod/import-resources-1683102212284-fetch-repo-pod           Container image "cgr.dev/chainguard/busybox@sha256:19f02276bf8dbdd62f069b922f10c65262cc34b710eea26ff928129a736be791" already present on machine
tekton-dashboard   27s         Normal    Started                   pod/import-resources-1683102212284-fetch-repo-pod           Started container place-scripts
tekton-dashboard   27s         Normal    Started                   pod/affinity-assistant-9b19aeb6cb-0                         Started container affinity-assistant
tekton-dashboard   27s         Normal    Created                   pod/affinity-assistant-9b19aeb6cb-0                         Created container affinity-assistant
tekton-dashboard   27s         Normal    Pulled                    pod/affinity-assistant-9b19aeb6cb-0                         Container image "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.47.0@sha256:3bd15d5ea0f19f439c02bc629d04b5759ec0f4e01e84f1963f3533b7e96643c4" already present on machine
tekton-dashboard   27s         Normal    Created                   pod/import-resources-1683102212284-fetch-repo-pod           Created container place-scripts
tekton-dashboard   26s         Normal    Started                   pod/import-resources-1683102212284-fetch-repo-pod           Started container step-clone
tekton-dashboard   26s         Normal    Created                   pod/import-resources-1683102212284-fetch-repo-pod           Created container step-clone
tekton-dashboard   26s         Normal    Pulled                    pod/import-resources-1683102212284-fetch-repo-pod           Container image "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.41.0" already present on machine
tekton-dashboard   26s         Normal    Pending                   taskrun/import-resources-1683102212284-fetch-repo           pod status "Ready":"False"; message: "containers with unready status: [step-clone]"
tekton-dashboard   25s         Normal    Running                   taskrun/import-resources-1683102212284-fetch-repo           Not all Steps in the Task have finished executing
tekton-dashboard   22s         Warning   Failed                    pipelinerun/import-resources-1683102212284                  Tasks Completed: 1 (Failed: 1, Cancelled 0), Skipped: 1
tekton-dashboard   22s         Normal    Killing                   pod/affinity-assistant-9b19aeb6cb-0                         Stopping container affinity-assistant
tekton-dashboard   22s         Warning   Failed                    taskrun/import-resources-1683102212284-fetch-repo           "step-clone" exited with code 1 (image: "docker-pullable://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init@sha256:249081d967c05371fecf9c6ed423fa9cafbfcb2a206c5d5df5d5249859458160"); for logs run: kubectl -n tekton-dashboard logs import-resources-1683102212284-fetch-repo-pod -c step-clone
```

**Comment by AlanGreene** [comment] 2023-05-03 11:10
Hi @R3DRUN3, thanks for reporting this. I've just run through the tutorial successfully and was unable to reproduce the issue.

I used the same kubernetes and Tekton versions you mentioned, and the latest minikube:

```sh
$ minikube version
minikube version: v1.30.1
commit: 08896fd1dc362c097c925146c4a0d0dac715ace0

$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-14T13:14:41Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/arm64"}

$ tkn version
Client version: 0.30.1
Pipeline version: v0.47.0
Dashboard version: v0.35.0
```

If you delete the cluster (`minikube delete --profile tekton-dashboard-tutorial`) and create a new one do you encounter the issue consistently?

**Comment by R3DRUN3** [comment] 2023-05-03 12:02
@AlanGreene for whatever reason I was creating the minikube cluster with `minikube start --nodes=3` instead of `minikube start --profile tekton-dashboard-tutorial`...with the latter it works.
Curious on why it does not work with the former 🤔

**Comment by AlanGreene** [comment] 2023-05-03 12:05
Interesting, thanks for the extra info. I'll try to reproduce it with that change and see if there's anything we need to do to handle it differently.

Since the original reported problem is resolved and the tutorial works as expected I'll close this issue.

**Closed by AlanGreene** 2023-05-03 12:05 UTC
Labels: kind/bug

**Comment by AlanGreene** [comment] 2023-05-03 12:23
Looks like the issue is most likely due to the default storage config. From the minikube tutorial https://minikube.sigs.k8s.io/docs/tutorials/multi_node/
> Caveat
Default [host-path volume provisioner](https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/) doesn’t support multi-node clusters ([#12360](https://github.com/kubernetes/minikube/issues/12360)). To be able to provision or claim volumes in multi-node clusters, you could use [CSI Hostpath Driver](https://minikube.sigs.k8s.io/docs/tutorials/volume_snapshots_and_csi/) addon.

So the cluster would need to be prepared before running any Tekton workload requiring the use of workspaces / volumes.

**Comment by R3DRUN3** [comment] 2023-05-03 12:32
@AlanGreene thank you very much, will keep it in mind!
