### ISSUE TITLE
Rebuild button can error for an already rebuilt PipelineRun

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#440] opened 2019-08-20 10:09 UTC
Tried to rebuild a PipelineRun and got an error 
It may be because it was a rebuild of a rebuild
This was on 0.6.0 pipelines 

```
{"level":"debug","msg":"in RebuildPipelineRun"}
{"level":"debug","msg":"Request data: {simple-pipeline-insecure-run-1566291656266-r-09400}"}
{"level":"debug","msg":"No name has been provided and a request has been made to rebuild with the name of an existing PipelineRun"}
{"level":"debug","msg":"Rebuilding PipelineRun: simple-pipeline-insecure-run-1566291656266-r-09400"}
{"level":"debug","msg":"in rebuildImpl"}
{"level":"debug","msg":"Found the PipelineRun to rebuild (simple-pipeline-insecure-run-1566291656266-r-09400 in namespace tekton-pipelines)"}
{"level":"debug","msg":"Rebuilt PipelineRun name: simple-pipeline-insecure-run-1566291656266-r-09400"}
{"level":"debug","msg":"Didn't find any existing labels, so creating a new one"}
{"level":"debug","msg":"new PipelineRun data is: &{{ } {simple-pipeline-insecure-run-1566291656266-r-09400  tekton-pipelines /apis/tekton.dev/v1alpha1/namespaces/tekton-pipelines/pipelineruns/simple-pipeline-insecure-run-1566291656266-r-09400 f4f476e5-c32f-11e9-b0a7-025000000001  1 2019-08-20 09:50:35 +0000 UTC <nil> <nil> map[rebuilds:simple-pipeline-insecure-run-1566291656266-r-09400] map[kubectl.kubernetes.io/last-applied-configuration:{\"apiVersion\":\"tekton.dev/v1alpha1\",\"kind\":\"Pipeline\",\"metadata\":{\"annotations\":{},\"name\":\"simple-pipeline-insecure\",\"namespace\":\"tekton-pipelines\"},\"spec\":{\"resources\":[{\"name\":\"git-source\",\"type\":\"git\"},{\"name\":\"docker-image\",\"type\":\"image\"}],\"tasks\":[{\"name\":\"build-simple\",\"resources\":{\"inputs\":[{\"name\":\"git-source\",\"resource\":\"git-source\"}],\"outputs\":[{\"name\":\"builtImage\",\"resource\":\"docker-image\"}]},\"taskRef\":{\"name\":\"kaniko-build-push\"}},{\"name\":\"deploy-simple\",\"resources\":{\"inputs\":[{\"name\":\"git-source\",\"resource\":\"git-source\"},{\"name\":\"image-out\",\"resource\":\"docker-image\"}]},\"runAfter\":[\"build-simple\"],\"taskRef\":{\"name\":\"deploy-simple-kubectl-task-insecure\"}}]}}\n] [] nil [] } {{simple-pipeline-insecure } [{git-source {git-source-1566229079573671400 }} {docker-image {docker-image-1566229079573671400 }}] [] tekton-dashboard [] <nil>  &Duration{Duration:1h0m0s,} {map[] [] nil nil []} map[] [] nil} {{0 [{Succeeded True  {2019-08-20 09:54:44 +0000 UTC} Succeeded All Tasks have completed executing}]} <nil> 2019-08-20 09:50:35 +0000 UTC 2019-08-20 09:54:44 +0000 UTC map[simple-pipeline-insecure-run-1566291656266-r-09400-build--rbnw5:0xc0008c1840 simple-pipeline-insecure-run-1566291656266-r-09400-deploy-gkflr:0xc0008c1960]}}"}
{"level":"error","msg":"an error occurred rebuilding the PipelineRun simple-pipeline-insecure-run-1566291656266-r-09400 in namespace tekton-pipelines: pipelineruns.tekton.dev \"simple-pipeline-insecure-run-1566291656266-r-09400\" already exists"}
{"level":"error","msg":"Error: pipelineruns.tekton.dev \"simple-pipeline-insecure-run-1566291656266-r-09400\" already exists"}
```

May be a more unique timestamp is needed

**Comment by a-roberts** [comment] 2019-08-30 10:47
Hmmm, I can't reproduce this on my set up

```
adams-mbp:src aroberts$ k get pipelinerun
NAME                                        SUCCEEDED   REASON    STARTTIME   COMPLETIONTIME
simple-pipeline-run-1567161667163           Unknown     Running   19s
simple-pipeline-run-1567161667163-r-77200   Unknown     Running   10s
simple-pipeline-run-1567161667163-r-81500   Unknown     Running   15s
```

That's with Tekton 0.5.2 and our latest dashboard code

I moved up to Tekton 0.6.0, rebuilt the same run (including rebuilds and just clicking rebuild on the original) and noticed no problems

FWIW this is on Docker Desktop

**Comment by a-roberts** [comment] 2019-09-02 09:14
I really can't reproduce this no matter what Tekton version or environment, I'm closing until we know more/can reproduce it ever again (please reopen if you ever can!)

**Closed by a-roberts** 2019-09-02 09:14 UTC
Labels: kind/bug
