### ISSUE TITLE
Support status of skipped steps (StepAction when expression)

### ISSUE THREAD

**Issue by uqix** [tektoncd/dashboard#3572] opened 2024-08-26 11:02 UTC
# Feature request

As `when` expression for `StepAction` has been [implemented](https://github.com/tektoncd/pipeline/blob/v0.62.2/docs/stepactions.md#controlling-step-execution-with-when-expressions), the status of skipped steps could be displayed in style like skipped tasks.

**Comment by AlanGreene** [comment] 2024-08-26 12:04
Thanks for the feature request @uqix, closing this as a duplicate of https://github.com/tektoncd/dashboard/issues/1445 which has yet to be implemented.

**Closed by AlanGreene** 2024-08-26 12:04 UTC
Labels: kind/feature
