### ISSUE TITLE
When creating a Secret (token based) I can not set annotation to set the server URL

### ISSUE THREAD

**Issue by rnapoles-tktn** [tektoncd/dashboard#1242] opened 2020-03-25 15:12 UTC
**Problem:**
Can not set Server URL for secret when using token

**Versions:**
OCP 4.3 / 4.4 RC1
Pipelines v0.10.1,  Triggers 0.3.1, Dashboard and webhooks v0.5.3

**Steps to reproduce:**
Install Tekton using versions listed above
Select Secrets tab
Click the Create + button
Provide a secret name 
Select NameSpace
Note that by default Password is set as Secret Type and Access to and Server URL can be set
Select Access Token as the secret type
Access to and URL can not be set

**Comment by a-roberts** [comment] 2020-04-03 09:47
Still seeing this in v0.6.0? I may have fixed this with https://github.com/tektoncd/dashboard/commit/a2f1d4807045948b64ee7409de9a17d3af9052d3

**Comment by AlanGreene** [comment] 2020-04-03 10:58
Does the pull request resource use the Tekton annotations at all? The example in the docs shows the resource explicitly referencing the relevant secret: https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#pull-request-resource

It's the same for the cluster and storage resources.

If this is the case, then I think this is working as intended since there's no need to set these annotations on an access token.

**Comment by a-roberts** [comment] 2020-04-03 12:00
> Does the pull request resource use the Tekton annotations at all? The example in the docs shows the resource explicitly referencing the relevant secret: https://github.com/tektoncd/pipeline/blob/master/docs/resources.md#pull-request-resource
> 
> It's the same for the cluster and storage resources.
> 
> If this is the case, then I think this is working as intended since there's no need to set these annotations on an access token.

Ah yes, actually that's right and this is why I added the tooltip (since you might think, oh I'll make an access token type secret for your PIpelineRuns to use, when really it's a password type one with annotations). I don't see a need for the Tekton annotations on the access tokens - if I'm wrong let's reopen this and display the additional fields, otherwise let's close this one out (@rnapoles-tktn if you think there's a need for it lemme know!)

**Closed by a-roberts** 2020-04-03 12:00 UTC

**Comment by rnapoles-tktn** [comment] 2020-04-03 13:14
@a-roberts we need the annotations for access tokens, otherwise how can specify if the access token is for github.com or github.ibm.com ?

**Comment by a-roberts** [comment] 2020-04-03 13:21
> @a-roberts we need the annotations for access tokens, otherwise how can specify if the access token is for github.com or github.ibm.com ?

But those are on password type secrets (the server URL being specified as github.com vs github.ibm.com in this case) - the access token type secret doesn't use annotations
