### ISSUE TITLE
PipelineRuns, PipelineResources and TaskRuns tables should have batch action bars to delete multiple at once

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/dashboard#1036] opened 2020-02-11 11:21 UTC
# Expected behavior

I should be able to delete multiple PipelineRuns, PipelineResources, and TaskRuns using a batch action bar, as with the secrets table.

# Actual behavior

I can only delete one of each of these resources at once.

# Steps to reproduce the problem

1. Create/import a resource in the dashboard that isn't a secret.
2. Try to delete more than one at once
3. You can't

# Environment
- Kubernetes Platform:

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

# Additional Info

**Comment by AlanGreene** [comment] 2020-02-11 11:40
Duplicate of https://github.com/tektoncd/dashboard/issues/966

**Closed by AlanGreene** 2020-02-11 11:40 UTC
