### ISSUE TITLE
Changing namespace when looking at a PipelineRun shouldn't bring up an error

### ISSUE THREAD

**Issue by CarolynMabbott** [tektoncd/dashboard#569] opened 2019-09-26 14:33 UTC
# Expected Behavior
Changing the namespace when looking at a PipelineRun should take me to the PipelinesRun page for that namespace 
# Actual Behavior
Changing the namespace when looking at a PipelineRun brings up an error 

# Steps to Reproduce the Problem

1. Look at a PipelineRun 
2. Change namespaces on the left hand side 
3. Error appears 

# Additional Info
Also it appears that when looking at a PipelineRun this shows on the left as Pipelines instead of PipelineRuns 

![Screenshot 2019-09-26 at 15 30 04](https://user-images.githubusercontent.com/32342288/65697288-960f7600-e072-11e9-85bc-60d9b3f98f5a.png)

**Comment by AlanGreene** [comment] 2019-09-26 15:52
Changing namespace on both the PipelineRun and TaskRun detail pages displays an error as it's updating the namespace in the URL and no matching 'Run' is found for the updated URL. This is consistent with the behaviour on the list pages where we update the UI to filter the list to the selected namespace.

The mismatch with the highlighted nav item (Pipelines) on the PipelineRun page is known: https://github.com/tektoncd/dashboard/issues/142#issuecomment-499579502. Posting on slack for discussion as it involves changing the URL used for the PipelineRun page, and also the TaskRun pages for consistency.

**Comment by AlanGreene** [comment] 2019-11-07 16:04
Updated designs remove the namespace dropdown on the details pages and only surface it on the lists where it currently behaves as expected.

**Comment by mnuttall** [comment] 2019-12-10 16:30
I'm closing this because I _think_ it . was fixed by https://github.com/tektoncd/dashboard/commit/30a0392fce08c2d25d7c666b922c935d5c8b7dc2. @CarolynMabbott please reopen if that's incorrect.

**Closed by mnuttall** 2019-12-10 16:30 UTC

**Comment by AlanGreene** [comment] 2019-12-10 17:16
Confirmed this is fixed by https://github.com/tektoncd/dashboard/pull/768
