### ISSUE TITLE
Log persistence documentation is out of date and configuration does not work with current version of operator

### ISSUE THREAD

**Issue by WTPascoe** [tektoncd/dashboard#2526] opened 2022-10-12 16:53 UTC
I am unable to helm install 3.6.0 of the logging operator on EKS running Kubernetes 1.23 - this fails with the following. Not unexpected since this release is 2 years old now :)

```
Helm install failed: failed to install CRD crds/logging.banzaicloud.io_clusterflows.yaml: resource mapping not found for name: "clusterflows.logging.banzaicloud.io" namespace: "" from "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
ensure CRDs are installed first
```

Installing `3.17.9` with helm works correctly, but as soon as the ClusterFlow is created with the config at https://github.com/tektoncd/dashboard/blob/main/docs/walkthrough/walkthrough-logs.md , the logging-operator begins to throw the following error and does not recover:

```
{"level":"error","ts":1665580485.7587454,"logger":"controller.logging","msg":"Reconciler error","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","name":"logging","namespace":"","error":"current config is invalid","errorVerbose":"current config is invalid\ngithub.com/banzaicloud/logging-operator/pkg/resources/fluentd.(*Reconciler).Reconcile\n\t/workspace/pkg/resources/fluentd/fluentd.go:138\ngithub.com/banzaicloud/logging-operator/controllers/logging.(*LoggingReconciler).Reconcile\n\t/workspace/controllers/logging/logging_controller.go:149\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227"}
```

I'm not sure whether the issue is in the ClusterOutput since that is not active until a ClusterFlow is applied.

In addition to this error in the `logging-operator` pod logs, I see the following failure on the `configcheck` pod after applying the clusterflow

```
logging-fluentd-configcheck-6e031eaf   0/1     Error       0          8s
```

Checking the log shows an error:

```
$ k logs logging-fluentd-configcheck-6e031eaf | tail -
n 5
2022-10-12 16:50:37 +0000 [info]: gem 'fluent-plugin-throttle' version '0.0.5'
2022-10-12 16:50:37 +0000 [info]: gem 'fluent-plugin-webhdfs' version '1.5.0'
2022-10-12 16:50:37 +0000 [info]: gem 'fluentd' version '1.14.6'
2022-10-12 16:50:37 +0000 [info]: starting fluentd-1.14.6 as dry run mode ruby="2.7.6"
2022-10-12 16:50:38 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="chunk_keys specification includes invalid char"
```

# Expected behaviour

On application of the ClusterFlow, I expect the logging configuration to be in a healthy state and forwarding logs to S3.

# Steps to reproduce the bug

```
helm upgrade --install --version 3.17.9 --wait --namespace logging logging-operator banzaicloud-stable/logging-operator
kubectl -n logging apply -f - <<EOF
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging
spec:
  fluentd: {}
  fluentbit: {}
  controlNamespace: tools
EOF
```

At this point, I have healthy pods and config check has passed. This remains the case after applying the clusteroutput.

```
NAME                                   READY   STATUS      RESTARTS   AGE
logging-fluentbit-httr4                1/1     Running     0          5m1s
logging-fluentbit-ljzxh                1/1     Running     0          5m1s
logging-fluentbit-xsp57                1/1     Running     0          5m1s
logging-fluentd-0                      2/2     Running     0          5m6s
logging-fluentd-configcheck-ac2d4553   0/1     Completed   0          5m10s
logging-operator-c975d7d64-xqm8t       1/1     Running     0          5m14s
```

I am not setting S3 keys as the user the pod runs as has permissions on the bucket via IRSA setup.

```
kubectl -n logging apply -f - <<EOF
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: s3-logging-output
  namespace: logging
spec:
  s3:
    s3_bucket: my-bucket-ffo7
    s3_region: my-aws-region
    store_as: text
    path: \${\$.kubernetes.namespace_name}/\${\$.kubernetes.pod_name}/\${\$.kubernetes.container_name}/
    buffer:
      tags: time,\$.kubernetes.namespace_name,\$.kubernetes.pod_name,\$.kubernetes.container_name
      timekey: 1m
      timekey_wait: 1m
      timekey_use_utc: true
    format:
      type: single_value
      message_key: message
EOF

kubectl -n logging apply -f - <<EOF
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: s3-logging-flow
  namespace: logging
spec:
  globalOutputRefs:
    - s3-logging-output
  match:
    - select:
        labels:
          app.kubernetes.io/managed-by: tekton-pipelines
EOF
````

After applying the clusterflow, the errors in the description begin to be thrown. In addition, the config check fails with the following output in the pod log. 

```
2022-10-12 16:50:38 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="chunk_keys specification includes invalid char"
```

Pods are now as follows:

```
NAME                                   READY   STATUS      RESTARTS   AGE
logging-fluentbit-httr4                1/1     Running     0          14m
logging-fluentbit-ljzxh                1/1     Running     0          14m
logging-fluentbit-xsp57                1/1     Running     0          14m
logging-fluentd-0                      2/2     Running     0          14m
logging-fluentd-configcheck-6e031eaf   0/1     Error       0          2m14s
logging-fluentd-configcheck-ac2d4553   0/1     Completed   0          14m
logging-operator-c975d7d64-xqm8t       1/1     Running     0          14m
```

# Environment details

- Kubernetes Platform:
AWS EKS
- Kubernetes or OpenShift version:
1.23
- Cloud-provider/provisioner:
AWS
- Versions:
   - Tekton Dashboard:
   
   - Tekton Pipelines:
   
   - Tekton Triggers:
   
- Install namespaces:
   - Tekton Dashboard:
      tekton-pipelines
   - Tekton Pipelines:
      tekton-pipelines
   - Tekton Triggers:
   tekton-pipelines

**Comment by AlanGreene** [comment] 2022-10-16 14:42
Thanks for raising this issue @WTPascoe. I've reclassified it as a documentation issue since it's not a bug with the Dashboard.

The walkthrough specifies the versions of the tools used, including the Kubernetes version known to work (currently 1.21). Running through the walkthrough as provided works as expected.

A PR to update the instructions to use more current versions, or to change it to point to current documentation for each of the tools used would be welcome.

**Comment by AlanGreene** [comment] 2022-12-07 12:49
The issue with use of PodSecurityPolicy that prevented installation of the logging operator on Kubernetes 1.25+ has been fixed in https://github.com/banzaicloud/logging-operator/releases/tag/3.17.10

**Comment by AlanGreene** [comment] 2023-02-20 15:38
PR #2743 open to update minio and the logging-operator to latest releases. Tested on Kubernetes 1.25 with latest Tekton releases as of today.

**Closed** 2023-02-20 16:08 UTC
Labels: kind/documentation
