### ISSUE TITLE
v0.24.1 Service not support NodePort

### ISSUE THREAD

**Issue by hrbust-liu** [tektoncd/dashboard#2318] opened 2022-03-01 11:19 UTC
# Describe the bug

**[tekton-dashboard-release.yaml] 
Service not deploy NodePort
I can't access it outside the cluster**

# Expected behaviour
Service yaml change to
`  ports:
    - name: http
      port: 9097
      protocol: TCP
      targetPort: 9097
  type: NodePort`

# Steps to reproduce the bug

# Environment details

- Kubernetes Platform:

- Kubernetes or OpenShift version:

- Install mode (if on OpenShift):

- Cloud-provider/provisioner:

- Versions:
   - Tekton Dashboard:
   
   - Tekton Pipelines:
   
   - Tekton Triggers:
   
- Install namespaces:
   - Tekton Dashboard:
   
   - Tekton Pipelines:
   
   - Tekton Triggers:
   

# Additional Info

**Comment by AlanGreene** [comment] 2022-03-01 11:50
Thanks for opening an issue @hrbust-liu. By default the Dashboard isn't exposed outside the cluster, this is by design. However, by default we do support 3 different methods of accessing the application depending on your needs:
- `kubectl proxy`
- `kubectl port-forward`
- using an `Ingress`

These are described in more detail in the documentation at https://github.com/tektoncd/dashboard/blob/main/docs/install.md#accessing-the-dashboard

If you still wish to use `NodePort` for some reason you can edit the `tekton-dashboard` Service as needed.

Closing as this is not a bug, but feel free to ask any follow-up questions either here or in the `#dashboard` channel on [Slack](https://github.com/tektoncd/community/blob/main/contact.md#slack)

**Closed by AlanGreene** 2022-03-01 11:50 UTC
Labels: kind/bug

**Comment by hrbust-liu** [comment] 2022-03-01 13:27
thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alan ***@***.***&gt;; 
发送时间: 2022年3月1日(星期二) 晚上7:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tektoncd/dashboard] v0.24.1 Service not support NodePort (Issue #2318)





 
Thanks for opening an issue @hrbust-liu. By default the Dashboard isn't exposed outside the cluster, this is by design. However, by default we do support 3 different methods of accessing the application depending on your needs:
  
kubectl proxy
 
kubectl port-forward
 
using an Ingress
  
These are described in more detail in the documentation at https://github.com/tektoncd/dashboard/blob/main/docs/install.md#accessing-the-dashboard
 
If you still wish to use NodePort for some reason you can edit the tekton-dashboard Service as needed.
 
Closing as this is not a bug, but feel free to ask any follow-up questions either here or in the #dashboard channel on Slack
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
