### ISSUE TITLE
Dashboard Deployment Crashes: Error while proxying request

### ISSUE THREAD

**Issue by TomHart** [tektoncd/dashboard#2411] opened 2022-08-04 10:31 UTC
# Describe the bug
The Tekton Dashboard Deployment crashes, seemingly when a Pipeline is running, but not narrowed down the exact thing that triggers the crash yet.

# Expected behaviour
Doesn't crash

# Steps to reproduce the bug
Unsure yet

# Environment details

- Kubernetes Platform:
k3s- Kubernetes or OpenShift version:

- Install mode (if on OpenShift):
Running on a local RPi 4
- Cloud-provider/provisioner:
N/A
- Versions:
   - Tekton Dashboard:
         0.28.0
   - Tekton Pipelines:
         0.38.0
   - Tekton Triggers:
         0.20.2
- Install namespaces:
   - Tekton Dashboard:
        tekton-pipelines
   - Tekton Pipelines:
        tekton-pipelines
   - Tekton Triggers:
        tekton-pipelines

# Additional Info
Error from the container, will get the full stack trace the next time it happens as it's gone now
```
tekton dashboard Error while proxying request: error dialing backend: dial tcp operation was canceled
```

**Comment by AlanGreene** [comment] 2022-08-11 10:53
Closing as I have been unable to reproduce the issue and have seen no other reports of this happening.

Feel free to reopen with additional details if it happens again.

**Closed by AlanGreene** 2022-08-11 10:53 UTC
Labels: kind/bug
